import type { NextPage } from "next";
import Head from "next/head";
import Main from "../components/Main";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script type="text/javascript"> document.write(typeof(window.ethereum)); </script> */}
      </Head>

      <div>
        <Main />
      </div>
    </div>
  );
};

export default Home;
